export const CALL_STATUSES = [
    { id: 'cita', label: 'Cita', color: 'bg-green-100 text-green-800' },
    { id: 'visitado', label: 'Visitado', color: 'bg-green-100 text-green-800' },
    { id: 'reprogramar', label: 'Reprogramar', color: 'bg-yellow-100 text-yellow-800' },
    { id: 'seguimiento', label: 'Seguimiento', color: 'bg-blue-100 text-blue-800' },
    { id: 'venta', label: 'Venta', color: 'bg-green-200 text-green-900 border-green-300 font-bold' },
    { id: 'buzon', label: 'Buzón', color: 'bg-gray-100 text-gray-800' },
    { id: 'no_contesta', label: 'No Contesta', color: 'bg-red-50 text-red-800' },
    { id: 'desconectado', label: 'Desconectado', color: 'bg-red-100 text-red-800' },
    { id: 'numero_incorrecto', label: 'Número Incorrecto', color: 'bg-red-100 text-red-800' },
    { id: 'repetido', label: 'Repetido', color: 'bg-orange-100 text-orange-800' },
    { id: 'llamar_en', label: 'Llamar en...', color: 'bg-purple-100 text-purple-800' },
    { id: 'compro_visitada', label: 'Compró o Visitada hace poco', color: 'bg-gray-100 text-gray-600' },
    { id: 'no_interesado', label: 'No Interesado', color: 'bg-red-200 text-red-900' },
    { id: 'recomprado', label: 'Recomprado', color: 'bg-green-50 text-green-700' },
    { id: 'moroso', label: 'Moroso', color: 'bg-red-100 text-red-800' },
    { id: 'no_califica', label: 'No Califica', color: 'bg-gray-200 text-gray-700' },
    { id: 'no_volver_contactar', label: 'No Volver a Contactar', color: 'bg-black text-white' },
    { id: 'otro_pais', label: 'Otro País', color: 'bg-gray-100 text-gray-600' },
    { id: 'otro_estado', label: 'Otro Estado', color: 'bg-gray-100 text-gray-600' },
    { id: 'otra_ciudad', label: 'Otra Ciudad', color: 'bg-gray-100 text-gray-600' },
];
